version: '3'

services:
  backend:
    build: 
      context: ./backend
    command: bash -c "python3 /app/manage.py migrate &&
      python3 /app/manage.py runserver 0.0.0.0:8000"
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
  
  frontend:
    image: presence_frontend:latest
    build: 
      context: ./frontend
    command: npm start
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
